services:
  localstack:
    image: 'localstack/localstack:4.4.0'
    environment:
      - 'SERVICES=sqs'
      - 'AWS_DEFAULT_REGION=us-east-1'
    ports:
      - '4566:4566'
    volumes:
      - './docker/localstack/init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh:ro'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    volumes:
      - './docker/grafana/dashboards:/otel-lgtm/custom-dashboards:ro'
      - './docker/grafana/provisioning/dashboards/dashboards.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/dashboards.yaml:ro'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
