-- ADR-003 §1, §3: enum types and the two non-partitioned input tables.

-- ADR-003 §1: the seven INTERNAL delivery states, not the three-value public
-- API vocabulary (pending/completed/failed) of ADR-003 §1.1. The public
-- vocabulary is produced by a controller-side mapping step and is never
-- stored, defaulted to, or constrained against here.
CREATE TYPE delivery_status AS ENUM (
  'PENDING', 'QUEUED', 'PROCESSING', 'RETRYING', 'DELIVERED', 'DEAD', 'FAILED'
);

-- ADR-005 §1: how a deliveries row came to exist.
CREATE TYPE delivery_origin AS ENUM ('INGEST', 'REPLAY', 'RECOVERED');

-- ADR-006 §1.2: per-subscription circuit breaker state.
CREATE TYPE circuit_state AS ENUM ('CLOSED', 'OPEN', 'HALF_OPEN');

-- ADR-005 §2: target-URL ownership handshake state.
CREATE TYPE verification_state AS ENUM ('PENDING_VERIFICATION', 'VERIFIED');

-- ADR-003 §3: immutable, append-only record of what the platform emitted.
-- event_id is the platform's own id (text, e.g. 'EVT001'), not a generated
-- UUID; being the PK is what makes the gateway's
-- INSERT ... ON CONFLICT (event_id) DO NOTHING idempotent (ADR-002 §1.1 step 3).
CREATE TABLE notification_events (
  event_id   text        PRIMARY KEY,
  client_id  text        NOT NULL,
  event_type text        NOT NULL,
  content    text        NOT NULL,
  created_at timestamptz NOT NULL
);

COMMENT ON TABLE notification_events IS
  'ADR-003 §3: append-only, immutable after insert. Never updated. No updated_at by design.';
COMMENT ON COLUMN notification_events.event_id IS
  'Platform-assigned id (e.g. EVT001), not a generated UUID. PK makes gateway ingest idempotent via ON CONFLICT DO NOTHING (ADR-002 §1.1 step 3).';
COMMENT ON COLUMN notification_events.created_at IS
  'Event-creation timestamp supplied by the caller (ADR-003 §3), NOT the row-insert time. No DEFAULT now() here: a default would silently mask a producer omission and corrupt the API date-range filter and client-side ordering that replaces sequence_number.';
COMMENT ON COLUMN notification_events.content IS
  'PII layer (ADR-002 §3.1). Store it; never log it, never place it on a span or in MDC.';

-- ADR-003 §3: the delivery contract with a client; also holds circuit-breaker
-- (ADR-006 §1.2), bulkhead (ADR-006 §1.3), throttle (ADR-004 §1) and
-- verification (ADR-005 §2) state.
CREATE TABLE subscriptions (
  subscription_id             uuid                NOT NULL,
  client_id                   text                NOT NULL,
  target_url                  text                NOT NULL,
  secret_ref                  text                NOT NULL,
  previous_secret_ref         text,
  previous_secret_expires_at  timestamptz,
  event_types                 text[]              NOT NULL,
  active                      boolean             NOT NULL DEFAULT true,
  verification_state          verification_state  NOT NULL DEFAULT 'PENDING_VERIFICATION',
  verified_at                 timestamptz,
  max_concurrency             int                 NOT NULL DEFAULT 10,
  circuit_state                circuit_state       NOT NULL DEFAULT 'CLOSED',
  circuit_opened_at           timestamptz,
  circuit_backoff              interval,
  consecutive_opens           int                 NOT NULL DEFAULT 0,
  throttled_until              timestamptz,
  created_at                  timestamptz         NOT NULL DEFAULT now(),
  updated_at                  timestamptz         NOT NULL DEFAULT now(),
  CONSTRAINT pk_subscriptions PRIMARY KEY (subscription_id)
);

COMMENT ON TABLE subscriptions IS
  'ADR-003 §3: delivery contract with a client, reused as the home of circuit-breaker/bulkhead/throttle/verification state (one join, no separate store). Subscription CRUD API is out of scope (ADR-003 §3).';
COMMENT ON COLUMN subscriptions.subscription_id IS
  'uuid, generated by the application, not by a column default - consistent with deliveries.delivery_id (TASK-002-03).';
COMMENT ON COLUMN subscriptions.event_types IS
  'text[], one row per client covering N event types. Replaces a unique(client_id, event_type) design (ADR-003 §3) - do not add that constraint.';
COMMENT ON COLUMN subscriptions.secret_ref IS
  'Reference to the HMAC secret, never the secret material itself (ADR-004 §2).';
COMMENT ON COLUMN subscriptions.previous_secret_ref IS
  'Reference only, non-null only while a secret rotation is in progress (ADR-004 §2).';
COMMENT ON COLUMN subscriptions.verification_state IS
  'Security control (OWASP A06), not a convenience default. DEFAULT PENDING_VERIFICATION: a subscription is never deliverable until its target URL operator answers the verification challenge (ADR-005 §2). Must never default to VERIFIED.';
COMMENT ON COLUMN subscriptions.consecutive_opens IS
  'Only breaker counter persisted (ADR-006 §1.2). The failure count itself is deliberately in-memory per pod to keep this row cold - there is no consecutive_failures column.';
COMMENT ON COLUMN subscriptions.circuit_backoff IS
  'interval, not a numeric seconds column: the relay due-query (ADR-002 §2.1) uses it directly as circuit_opened_at < now() - s.circuit_backoff.';

-- ADR-002 §1.1 step 2 / ADR-003 §2: ingest-time subscription lookup is
-- WHERE client_id = ? AND event_type = ? AND active, with event_type matched
-- against the event_types array. This query runs once per inbound event, so
-- it must not fall back to a sequential scan.
--
-- Shape chosen: a plain b-tree on (client_id, active) narrows to the
-- tenant's active subscriptions first (typically a small, low-cardinality
-- set per client), then a GIN index on event_types serves the array
-- containment test (a b-tree cannot). Two indexes, not a combined one,
-- because a b-tree and a GIN index are different access methods and
-- Postgres cannot build one composite index spanning both.
CREATE INDEX idx_subscriptions_client_active ON subscriptions (client_id, active);
CREATE INDEX idx_subscriptions_event_types ON subscriptions USING GIN (event_types);

COMMENT ON INDEX idx_subscriptions_client_active IS
  'Serves the WHERE client_id = ? AND active predicate of the ingest-time subscription lookup (ADR-002 §1.1 step 2, ADR-003 §2). Derived from that query, not requested by ADR-003 §3''s index list (which only covers deliveries).';
COMMENT ON INDEX idx_subscriptions_event_types IS
  'GIN index so event_type = ANY(event_types)-style containment on the ingest lookup does not force a sequential scan; a b-tree cannot serve array containment (ADR-002 §1.1 step 2).';
