-- ADR-003 §2, §3: the outbox table. Plain, unpartitioned (ADR-003 §3 -
-- partitioning is a deferred future improvement, not implemented here).

CREATE TABLE deliveries (
  delivery_id      uuid            NOT NULL,
  event_id         text            NOT NULL,
  subscription_id  uuid            NOT NULL,
  client_id        text            NOT NULL,
  status           delivery_status NOT NULL DEFAULT 'PENDING',
  origin           delivery_origin NOT NULL DEFAULT 'INGEST',
  replayed_from    uuid,
  attempt_count    int             NOT NULL DEFAULT 0,
  next_attempt_at  timestamptz,
  last_error       text,
  delivered_at     timestamptz,
  trace_context    text,
  created_at       timestamptz     NOT NULL DEFAULT now(),
  updated_at       timestamptz     NOT NULL DEFAULT now(),
  CONSTRAINT pk_deliveries PRIMARY KEY (delivery_id),
  CONSTRAINT fk_deliveries_event
    FOREIGN KEY (event_id) REFERENCES notification_events (event_id),
  CONSTRAINT fk_deliveries_subscription
    FOREIGN KEY (subscription_id) REFERENCES subscriptions (subscription_id),
  -- ON DELETE NO ACTION (the default): nothing in the ADRs deletes a
  -- deliveries row, so there is no scenario to design a cascade for.
  CONSTRAINT fk_deliveries_replayed_from
    FOREIGN KEY (replayed_from) REFERENCES deliveries (delivery_id)
);

COMMENT ON TABLE deliveries IS
  'ADR-003 §3: the outbox and sole source of truth for delivery state. Plain, unpartitioned table (ADR-003 §3 defers partitioning). At most one live (non-terminal) row per (event_id, subscription_id) at any time, enforced below by a native partial unique index - no side table, no trigger.';
COMMENT ON COLUMN deliveries.delivery_id IS
  'uuid, generated by the application, not by a column default (consistent with subscriptions.subscription_id, V1). This is the public notification_event_id the case''s endpoints operate on (ADR-003 §3).';
COMMENT ON COLUMN deliveries.client_id IS
  'Denormalized from subscriptions/notification_events on purpose: makes every tenant-scoped API query filterable without a join (OWASP A01).';
COMMENT ON COLUMN deliveries.replayed_from IS
  'Self-referential FK to deliveries.delivery_id. Used for both REPLAY and RECOVERED origins, disambiguated by the origin column (ADR-005 §1). No separate recovered_from column - that ADR-003 §1.1 mention is a documented slip.';
COMMENT ON COLUMN deliveries.next_attempt_at IS
  'Drives the relay due-query (ADR-002 §2.1) and the retry schedule (ADR-004 §1). Set to NULL on the DEAD transition (ADR-003 §1.1).';
COMMENT ON COLUMN deliveries.last_error IS
  'Denormalized snapshot of the latest attempt so the list endpoint need not join delivery_attempts for its common case (ADR-003 §3). Full history lives in delivery_attempts.';
COMMENT ON COLUMN deliveries.updated_at IS
  'Read by the relay due-query''s 60s staleness guard on PROCESSING rows (ADR-002 §2.1). No trigger maintains it - the writer (adapter layer) must set it explicitly on every UPDATE. Flagged as a hard constraint on the persistence adapter task.';

-- ADR-002 §2.1 (supersedes the narrower ADR-003 §3 version): the relay's
-- due-query index. Partial so DELIVERED/DEAD/FAILED rows leave it
-- automatically - the table may hold tens of millions of rows while this
-- index holds only what is outstanding.
CREATE INDEX idx_deliveries_due ON deliveries (next_attempt_at)
  WHERE status IN ('PENDING', 'RETRYING', 'QUEUED', 'PROCESSING');

-- ADR-003 §2, §3: the idempotency invariant, implemented natively. At most
-- one non-terminal row per (event_id, subscription_id). Two concurrent
-- inserts of a live row for the same pair are resolved by ordinary Postgres
-- unique-index insertion locking: one succeeds, one gets 23505 - no
-- check-then-write, no application-level race (OWASP A10 fails closed).
-- Once a row goes terminal it leaves the index's predicate, freeing the
-- pair for POST /replay (ADR-005 §1) or internal recovery (ADR-003 §1.1) to
-- insert a new row.
CREATE UNIQUE INDEX idx_deliveries_live_pair ON deliveries (event_id, subscription_id)
  WHERE status NOT IN ('DELIVERED', 'DEAD', 'FAILED');

-- ADR-003 §3, ADR-006 §1.3: per-subscription in-flight count for the
-- bulkhead / max_concurrency check. The counted statuses are QUEUED and
-- PROCESSING; kept as a plain (not partial) index since ADR-003 §3 asks
-- only for (subscription_id, status) and a partial index here would only
-- serve a query whose predicate matches exactly.
CREATE INDEX idx_deliveries_subscription_status ON deliveries (subscription_id, status);

-- ADR-003 §3: chains a replay's or recovery's history back to its
-- original. A FK does not create an index on the referencing side.
CREATE INDEX idx_deliveries_replayed_from ON deliveries (replayed_from);

-- ADR-003 §3, ADR-005 §1: the list endpoint's default ordering and
-- date-range filter, keyset-paginated.
CREATE INDEX idx_deliveries_client_created_at ON deliveries (client_id, created_at);

-- ADR-003 §3: the delivery_status filter. The API's public vocabulary is
-- expanded to internal states before reaching SQL; this indexes the
-- internal status column.
CREATE INDEX idx_deliveries_client_status ON deliveries (client_id, status);

COMMENT ON INDEX idx_deliveries_due IS
  'ADR-002 §2.1 relay due-query: status IN (...) AND next_attempt_at <= now(), ORDER BY next_attempt_at.';
COMMENT ON INDEX idx_deliveries_live_pair IS
  'ADR-003 §2 idempotency invariant. The single mechanism - no side table, no trigger, no application-level check.';
COMMENT ON INDEX idx_deliveries_subscription_status IS
  'ADR-006 §1.3 bulkhead: per-subscription in-flight count over QUEUED/PROCESSING rows.';
COMMENT ON INDEX idx_deliveries_replayed_from IS
  'Chains a REPLAY/RECOVERED row back to its original (ADR-005 §1, ADR-003 §1.1).';
COMMENT ON INDEX idx_deliveries_client_created_at IS
  'GET /notification_events default ordering and date-range filter, keyset-paginated (ADR-005 §1).';
COMMENT ON INDEX idx_deliveries_client_status IS
  'delivery_status filter on the list endpoint, applied against the internal status column.';
